# Quarterly objectives with repos and contributors per objective
# Auto-generated by dse_oss_reports.generator. Do not edit by hand.
# - Objectives: Issues with pi-X.Y-objective labels
# - Contributors: Issue assignees
# - Repos: Labels matching repo:org/repo-name
OBJECTIVES = {
    "pi-26.2": [
        {
            "issue_number": 1,
            "title": "[Sc] PI 26.2 Objective 1: Hub Support",
            "state": "closed",
            "contributors": [
                ("Alex I. Mandel", "wildintellect"),
                ("Julia Signell", "jsignell"),
            ],
            "repos": [
                ("jupyterhub", "repo2docker-action"),
                ("pangeo-data", "pangeo-docker-images"),
                ("NASA-IMPACT", "pangeo-notebook-veda-image"),
            ],
        },
        {
            "issue_number": 2,
            "title": "[Sc] PI 26.2 Objective 2: Cloud Optimized Workflows",
            "state": "closed",
            "contributors": [
                ("Alex I. Mandel", "wildintellect"),
                ("Julia Signell", "jsignell"),
            ],
            "repos": [
                ("NASA-IMPACT", "veda-docs"),
                ("MAAP-Project", "maap-documentation"),
                ("cloudnativegeo", "cloud-optimized-geospatial-formats-guide"),
            ],
        },
        {
            "issue_number": 3,
            "title": "[Sc] PI 26.2 Objective 3: Open-Source Contributions",
            "state": "closed",
            "contributors": [
                ("Julia Signell", "jsignell"),
                ("Ian Cooke", "ircwaves"),
                ("Tyler", "tylanderson"),
            ],
            "repos": [
                ("radiantearth", "stac-best-practices"),
                ("radiantearth", "stac-spec"),
                ("dask", "dask"),
                ("stac-utils", "pystac"),
                ("stac-utils", "pystac-client"),
                ("pydata", "xarray"),
            ],
        },
        {
            "issue_number": 9,
            "title": "[Sc] PI 26.2 Objective 4: Data Retention Policy",
            "state": "closed",
            "contributors": [
                ("Sheyenne Kirkland", "smk0033"),
            ],
            "repos": [
            ],
        },
        {
            "issue_number": 10,
            "title": "[Sc] PI 26.2 Objective 5: VEDA Forum (Stretch)",
            "state": "closed",
            "contributors": [
                ("Sheyenne Kirkland", "smk0033"),
            ],
            "repos": [
            ],
        },
        {
            "issue_number": 11,
            "title": "[Sc] PI 26.2 Objective 6: AI Embedding Report (Stretch)",
            "state": "closed",
            "contributors": [
                ("Rajat Shinde", "omshinde"),
            ],
            "repos": [
            ],
        },
        {
            "issue_number": 12,
            "title": "[Sc] PI 26.2 Objective 7: Merge MAAP Documentation into VEDA (Stretch)",
            "state": "closed",
            "contributors": [
            ],
            "repos": [
            ],
        },
    ],
    "pi-26.3": [
        {
            "issue_number": 31,
            "title": "[Sc] PI 26.3 Objective 1: Hub Upgrades",
            "state": "open",
            "contributors": [
                ("Alex I. Mandel", "wildintellect"),
                ("Grace Llewellyn", "grallewellyn"),
            ],
            "repos": [
                ("jupyterhub", "repo2docker-action"),
                ("pangeo-data", "pangeo-docker-images"),
                ("NASA-IMPACT", "pangeo-notebook-veda-image"),
            ],
        },
        {
            "issue_number": 32,
            "title": "[Sc] PI 26.3 Objective 2: Cloud Optimized Workflows",
            "state": "open",
            "contributors": [
                ("Alex I. Mandel", "wildintellect"),
                ("Tyler", "tylanderson"),
            ],
            "repos": [
                ("NASA-IMPACT", "veda-docs"),
                ("MAAP-Project", "maap-documentation"),
                ("cloudnativegeo", "cloud-optimized-geospatial-formats-guide"),
            ],
        },
        {
            "issue_number": 33,
            "title": "[Sc] PI 26.3 Objective 3: Open-Source Contributions",
            "state": "open",
            "contributors": [
                ("Pete Gadomski", "gadomski"),
                ("Tyler", "tylanderson"),
            ],
            "repos": [
                ("radiantearth", "stac-best-practices"),
                ("radiantearth", "stac-spec"),
                ("dask", "dask"),
                ("stac-utils", "pystac"),
                ("stac-utils", "pystac-client"),
                ("pydata", "xarray"),
            ],
        },
        {
            "issue_number": 34,
            "title": "[Sc] PI 26.3 Objective 4: Data Retention Policy",
            "state": "open",
            "contributors": [
                ("Sheyenne Kirkland", "smk0033"),
            ],
            "repos": [
            ],
        },
    ],
}
